### ISSUE TITLE
error on url

### ISSUE THREAD

**Issue by shivarasan** [Aapps/PushNotificationGcmClient#1]
![capt](https://cloud.githubusercontent.com/assets/17755704/15771535/1878c79e-2989-11e6-8f90-67dc3203da24.PNG)

**Comment by neurobin** [comment]
Are you running on localhost?

**Comment by shivarasan** [comment]
yes of course

**Comment by shivarasan** [comment]
i use my local server

**Comment by neurobin** [comment]
check if your localhost is accessible, you can run an emulator and its browser and see if going to that ip works or not. And if you are testing with real device, then make sure your device and localhost are connected in the same network...

**Comment by shivarasan** [comment]
thanks u so much sir
finally i got notification
i correct the url 
then it's work perfect
